services:
  mongo:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"  # MongoDBのデフォルトポート
    volumes:
      - ./mongo-data:/data/db        # データ永続化
      - ./mongo-config/mongo-config.yml:/etc/mongo/mongo-config.yml  # 設定ファイルをマウント
    command: ["mongod", "--config", "/etc/mongo/mongo-config.yml"]  # 設定ファイルを指定

  node:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:  # 環境変数を指定
      - MONGO_URI=mongodb://mongo:27017/matchingApp
    command: npm start
    depends_on:
      - mongo

volumes:
  mongo-data:  # ボリュームを宣言