version: '3.8'
services:
  mongo:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"  # MongoDBのデフォルトポート
    volumes:
      - ./mongo-data:/data/db        # データ永続化
      - ./mongo-config:/etc/mongo    # 設定ファイルをマウント

  node:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:  # 環境変数を指定
      - MONGO_URI=mongodb://mongo:27017/matchingApp
    command: npm start
    depends_on:
      - mongo

volumes:
  mongo-data:  # ボリュームを宣言




# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - mongo
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/mydatabase

#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:
